import { categories } from "@/constants/categories.constants";

export const brandArrays = categories.map((category) => {
  switch (category.name) {
    case "Phones":
      return {
        category: category.name,
        brands: [
          "Apple",
          "Samsung",
          "Google",
          "OnePlus",
          "Xiaomi",
          "Huawei",
          "Nokia",
          "Sony",
          "LG",
          "Motorola",
          "HTC",
          "ASUS",
          "Lenovo",
          "Oppo",
          "Vivo",
          "Realme",
          "BlackBerry",
          "Alcatel",
          "Infinix",
          "Tecno",
          "Micromax",
          "Meizu",
          "ZTE",
          "Sharp",
          "Panasonic",
          "TCL",
          "Honor",
          "Lava",
          "LeEco",
          "Ulefone",
          "Wiko",
          "BQ",
          "Xolo",
          "Yota",
          "Kyocera",
          "Yu",
          "Zopo",
          "Archos",
          "Essential",
          "Sirin Labs",
          "Vertu",
          "CAT",
          "YU",
          "Fairphone",
          "Symphony",
          "Walton",
          "Maxwest",
          "BLU",
          "DOOGEE",
        ],
      };
    case "Laptops Computers":
      return {
        category: category.name,
        brands: [
          "Dell",
          "HP",
          "Apple",
          "Lenovo",
          "Acer",
          "Asus",
          "Microsoft",
          "MSI",
          "Samsung",
          "LG",
          "Razer",
          "Huawei",
          "Google",
          "Toshiba",
          "Sony",
          "Fujitsu",
          "Alienware",
          "Gateway",
          "Xiaomi",
          "Avita",
          "Surface",
          "Vaio",
          "Chuwi",
          "Medion",
          "LG Gram",
          "Gigabyte",
          "Fujitsu-Siemens",
          "Panasonic",
          "Clevo",
          "Compal",
          "Porsche Design",
          "System76",
          "Schenker",
          "Vizio",
          "LG Electronics",
          "HCL",
          "MSI Gaming",
          "Samsung Electronics",
          "Google Pixelbook",
          "Lenovo Legion",
          "Aorus",
          "LG Ultra",
          "Nvidia",
          "Haier",
          "Vizio",
          "Sager",
          "XMG",
          "Lenovo ThinkPad",
        ],
      };
    case "Accessories":
      return {
        category: category.name,
        brands: [
          "Apple",
          "Samsung",
          "Sony",
          "Logitech",
          "Bose",
          "JBL",
          "Razer",
          "Anker",
          "Belkin",
          "Jabra",
          "UE",
          "Sennheiser",
          "Philips",
          "Plantronics",
          "Beats",
          "Fitbit",
          "Garmin",
          "Huawei",
          "Xiaomi",
          "GoPro",
          "Canon",
          "Nikon",
          "SanDisk",
          "Seagate",
          "Western Digital",
          "Transcend",
          "Lexar",
          "Kingston",
          "Corsair",
          "HyperX",
          "SteelSeries",
          "Turtle Beach",
          "Astro",
          "AmazonBasics",
          "Microsoft",
          "HUAWEI",
          "LG",
          "Mophie",
          "OtterBox",
          "UAG",
          "Spigen",
          "LifeProof",
          "PowerA",
          "Caseology",
          "PopSockets",
          "TP-Link",
        ],
      };
    case "Headphones Earphones":
      return {
        category: category.name,
        brands: [
          "Sony",
          "Sennheiser",
          "Bose",
          "Audio-Technica",
          "JBL",
          "Beats",
          "AKG",
          "Skullcandy",
          "Philips",
          "Plantronics",
          "Jabra",
          "Shure",
          "Beyerdynamic",
          "FiiO",
          "Samsung",
          "Apple",
          "LG",
          "Xiaomi",
          "Huawei",
          "RHA",
          "Bowers & Wilkins",
          "Marshall",
          "TaoTronics",
          "Soundcore",
          "Panasonic",
          "Grado",
          "Anker",
          "Razer",
          "JVC",
          "Mpow",
          "AKG",
          "Master & Dynamic",
          "Jaybird",
          "1MORE",
          "V-Moda",
          "HyperX",
          "Etymotic",
          "Astro",
          "Audiofly",
          "Ultimate Ears",
          "Koss",
          "Beats by Dre",
          "COWIN",
          "Bose QuietComfort",
          "Beats Solo",
          "Philips SHP",
          "Beats Studio",
          "Bose SoundLink",
        ],
      };
    case "Wearable Tech":
      return {
        category: category.name,
        brands: [
          "Apple",
          "Samsung",
          "Fitbit",
          "Garmin",
          "Xiaomi",
          "Huawei",
          "Fossil",
          "Amazfit",
          "Polar",
          "Sony",
          "Honor",
          "Withings",
          "Misfit",
          "TicWatch",
          "Motorola",
          "Suunto",
          "Casio",
          "Garmin",
          "Oppo",
          "TCL",
          "Emporio Armani",
          "LG",
          "Tag Heuer",
          "Lenovo",
          "Pebble",
          "Nubia",
          "Skagen",
          "Tizen",
          "Ticwear",
          "Mobvoi",
          "Wear OS",
          "Xiaomi Mi Band",
          "Galaxy Watch",
          "Xiaomi Amazfit",
          "Garmin Vivoactive",
          "Huawei Watch",
          "Garmin Forerunner",
          "Fitbit Versa",
          "Fitbit Charge",
          "Apple Watch Series",
          "Samsung Gear",
          "Garmin Fenix",
          "Fitbit Ionic",
          "Fitbit Alta",
          "Fitbit Inspire",
        ],
      };
    case "Gaming":
      return {
        category: category.name,
        brands: [
          "Sony",
          "Microsoft",
          "Nintendo",
          "Razer",
          "Logitech",
          "SteelSeries",
          "Corsair",
          "ASUS",
          "MSI",
          "Acer",
          "Alienware",
          "HP",
          "Dell",
          "Xbox",
          "PlayStation",
          "Nintendo Switch",
          "HyperX",
          "Sennheiser",
          "Turtle Beach",
          "Roccat",
          "HORI",
          "Thrustmaster",
          "Mad Catz",
          "Saitek",
          "Plantronics",
          "JBL",
          "Bose",
          "Beyerdynamic",
          "Creative",
          "BenQ",
          "AOC",
          "ViewSonic",
          "LG",
          "Samsung",
          "ASRock",
          "GIGABYTE",
          "EVGA",
          "MSI Gaming",
          "ASUS ROG",
          "ZOTAC",
          "XFX",
          "PowerColor",
          "Sapphire",
          "Gigabyte Aorus",
          "PNY",
          "Galax",
          "Gainward",
          "Colorful",
          "Palit",
        ],
      };
    case "Cameras and Photography":
      return {
        category: category.name,
        brands: [
          "Canon",
          "Nikon",
          "Sony",
          "Panasonic",
          "Fujifilm",
          "Olympus",
          "Leica",
          "Samsung",
          "Pentax",
          "Hasselblad",
          "Phase One",
          "Ricoh",
          "Sigma",
          "Tamron",
          "Tokina",
          "Zeiss",
          "GoPro",
          "DJI",
          "Kodak",
          "Hikvision",
          "Arlo",
          "Insta360",
          "Nest",
          "Ring",
          "Sony Alpha",
          "Canon EOS",
          "Nikon D",
          "Sony Cyber-shot",
          "Fujifilm X",
          "Panasonic Lumix",
          "Olympus OM-D",
          "Leica M",
          "Pentax K",
          "Ricoh GR",
          "GoPro HERO",
          "DJI Osmo",
          "Nest Cam",
          "Ring Video Doorbell",
        ],
      };
    case "Home Electronics":
      return {
        category: category.name,
        brands: [
          "Samsung",
          "LG",
          "Panasonic",
          "Sony",
          "Toshiba",
          "Philips",
          "Sharp",
          "Hitachi",
          "Bosch",
          "Electrolux",
          "Siemens",
          "Whirlpool",
          "Kenwood",
          "Haier",
          "Mitsubishi",
          "TCL",
          "Indesit",
          "Daikin",
          "Carrier",
          "Trane",
          "Lennox",
          "Frigidaire",
          "Sanyo",
          "Onida",
          "Godrej",
          "Videocon",
          "Voltas",
          "Micromax",
          "Sansui",
          "Orient",
          "Bajaj",
          "Crompton",
          "Havells",
          "Usha",
          "Maharaja Whiteline",
          "Oppo",
          "Pigeon",
          "Kent",
          "Pureit",
          "Eureka Forbes",
          "HUL",
          "Livpure",
          "Blue Star",
          "LG Electronics",
          "Samsung Electronics",
        ],
      };
    case "Kitchen Appliances":
      return {
        category: category.name,
        brands: [
          "Philips",
          "Prestige",
          "Bajaj",
          "Morphy Richards",
          "Panasonic",
          "Usha",
          "Havells",
          "Kent",
          "Maharaja Whiteline",
          "Preethi",
          "LG",
          "Samsung",
          "Crompton",
          "Inalsa",
          "Butterfly",
          "Boss",
          "Black & Decker",
          "Havells",
          "Kaff",
          "Siemens",
          "Oster",
          "Faber",
          "Hindware",
          "V-Guard",
          "Godrej",
          "Sunflame",
          "AO Smith",
          "Koryo",
          "Ariston",
          "Vidiem",
          "Faber",
          "Whirlpool",
          "Elica",
          "Hafele",
          "Franke",
          "Carysil",
          "Pigeon",
          "Tupperware",
          "Milton",
          "Tupperware",
          "Kent RO",
          "HUL",
          "Eureka Forbes",
        ],
      };
    case "Office Electronics":
      return {
        category: category.name,
        brands: [
          "HP",
          "Canon",
          "Epson",
          "Brother",
          "Samsung",
          "Dell",
          "Lexmark",
          "Xerox",
          "Ricoh",
          "Kyocera",
          "Sharp",
          "Panasonic",
          "Toshiba",
          "OKI",
          "Fujitsu",
          "Konica Minolta",
          "Olivetti",
          "Kodak",
          "Citizen",
          "Primera",
          "Riso",
          "Pantum",
          "Gestetner",
          "Duplo",
          "Nashuatec",
          "Sawgrass",
          "Nixdorf",
          "NCR",
          "Datacard",
          "Dymo",
          "Pitney Bowes",
          "NCR Corporation",
          "Neopost",
          "Digital Check",
          "Polaroid",
          "Rimage",
          "TallyGenicom",
          "TSC",
          "Unisys",
          "Zebra",
          "SATO",
          "Datalogic",
          "Symbol",
          "Intermec",
        ],
      };
    case "Drones and Accessories":
      return {
        category: category.name,
        brands: [
          "DJI",
          "Parrot",
          "Yuneec",
          "Autel Robotics",
          "Syma",
          "Hubsan",
          "Holy Stone",
          "Potensic",
          "Ryze Tech",
          "DROCON",
          "Force1",
          "UPair",
          "Cheerson",
          "JJRC",
          "Eachine",
          "WLtoys",
          "DBPOWER",
          "UDI RC",
          "Visuo",
          "Contixo",
          "SGOTA",
          "Snaptain",
          "Tello",
          "Haktoys",
          "LBLA",
          "Altair Aerial",
          "Sky Viper",
          "Dromida",
          "Protocol",
          "Vivitar",
          "RUKO",
          "GoolRC",
          "DROCON",
          "Holy Stone",
          "Potensic",
          "Altair Aerial",
          "Hubsan",
          "Cheerson",
          "JJRC",
          "Eachine",
          "Tello",
          "Snaptain",
          "LBLA",
          "SGOTA",
        ],
      };
    default:
      return { category: category.name, brands: ["Other"] };
  }
});
